GET http://localhost:8080/api/books
Content-Type: application/json

###
GET http://localhost:8080/api/books/1

###

POST http://localhost:8080/api/books2
Content-Type: application/json

{
    "title": "The Beautiful and the Damned",
    "description": "They are one and the same.",
    "language": "English",
    "pages": 353
}

###
PUT http://localhost:8080/api/books2/3
Content-Type: application/json

{
    "title": "The Genius",
    "description": "A well-meaning idiot tries to survive in Russia",
    "language": "Cyrillic",
    "pages": 524
}

###
DELETE http://localhost:8080/api/books/5
###