GET http://localhost:8080/api/dojos
Content-Type: application/json

###
GET http://localhost:8080/api/ninjas
Content-Type: application/json

###
GET http://localhost:8080/api/dojos/1

###

POST http://localhost:8080/api/dojos2
Content-Type: application/json

{
    "name":"Bob's Burgers"
}

###
POST http://localhost:8080/api/ninjas2
Content-Type: application/json

{
    "firstName": "Sideshow",
    "lastName": "Bob",
    "age": 37,
    "dojoId": 2
}

###
POST http://localhost:8080/api/books2
Content-Type: application/json

{
    "title": "The Slow Regard of Silent Things",
    "author": "Patrick Rothfuss",
    "thoughts": "Whether or not something is a waste of time, is up to the one who decides whether or not to waste."
}

###
DELETE http://localhost:8080/api/books/5
###